apiVersion: apps/v1
kind: Deployment
metadata:
  name: transac-ai-iss-gke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transac-ai-iss
  template:
    metadata:
      labels:
        app: transac-ai-iss
    spec:
      containers:
        - name: iss-app
          image: us-east1-docker.pkg.dev/transac-ai/iss-repo/transac-ai-iss-gke:1.0.0
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: transac-ai-iss-secrets
                  key: transac-ai-iss-database-url
            - name: DIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: transac-ai-iss-secrets
                  key: transac-ai-iss-direct-url
            - name: TRANSAC_AI_ISS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: transac-ai-iss-secrets
                  key: transac-ai-iss-api-key
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
              ephemeral-storage: '256Mi'
            limits:
              memory: '512Mi'
              cpu: '200m'
              ephemeral-storage: '500Mi'
