# Load balancer to access the transac-ai-iss deployment
apiVersion: v1
kind: Service
metadata:
  name: transac-ai-iss-service
  annotations:
    networking.gke.io/load-balancer-type: 'Internal'
spec:
  type: LoadBalancer
  selector:
    app: transac-ai-iss
  ports:
    - name: tcp-port
      protocol: TCP
      port: 80
      targetPort: 4000
